server:
  port: 8084

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/orderinventorydb}

order:
  service:
    url: ${ORDER_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
