server:
  port: 8081

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/orderinventorydb}

inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
