server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/orderinventorydb}
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/orders/**
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/inventory/**
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/payments/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info
